### ISSUE TITLE
Mouse movements are not registering when moving fast with wasd

### ISSUE THREAD

**Issue by vijaybritto** [KilledByAPixel/BounceBack#1]
First of all this is an amazing game. One small bug i noticed was that when I was moving around the mouse '+' cursor doesnt move until I stop the wasd keypress. I think the keypress events are blocking the thread somewhere

**Comment by KilledByAPixel** [comment]
Thanks! That's weird, I don't seem to have the problem in Chrome or FireFox. Which browser are you using?

**Comment by vijaybritto** [comment]
It's chrome latest on windows. I'll be debugging it today. I'll let you know if I find anything

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MaxBittker** [comment]
I experienced this too but the game was still playable

**Comment by KilledByAPixel** [comment]
Are you using a touchpad?

**Comment by MaxBittker** [comment]
yes on a laptop

**Comment by KilledByAPixel** [comment]
Aha! By default most operating systems will disable trackpad input while typing. This happens automatically at the OS level so we have no control over it.

You can check in your device settings for the mouse or touchpad, there is probably something called palmcheck or touchcheck that you can disable. Another option is to connect a usb mouse.

I also have recently added game pad support to the extended version: http://bounceback.3d2k.com

**Comment by MaxBittker** [comment]
Ah :) thanks! I had experienced this before but didn’t understand it
